joomla/jissues

- templates/tracker/issues.index.twig
- www/jtracker/core/css/template.css
This PR will replace non alpha numeric characters in category name from the categories filter and will allow permalink button to work correctly.
But to make it work all aliases of the categories should be named (renamed) using the common pattern:
1. Spaces and non alpha numeric characters should be replaced with dash. 
2. Short names are not allowed
For example:
```
Router / Sef - router-sef
External Library - external-library
Language & Strings - language-strings
Templates (admin) - templates-admin
```
Also this PR will add `created_by` to permalink button.
As always you are welcome to test it on my [JIssues test website](http://jtracker.j4devs.ru/tracker/jtests)
> Fix #584 - permalink button

- templates/tracker/issue.edit.twig
This PR let the easy test option only show if we have code.
I think there is no real need to mark a Issue as `easy test` as nothing is to test there.
> Show the easy test option only if we have code.

- composer.json
- src/App/Tracker/Model/IssueModel.php
- templates/fields.twig
- templates/tracker/issue.edit.twig
"If the value attribute is not specified, the content will be passed as a value instead." (http://www.w3schools.com/tags/att_option_value.asp - the most reliable source ever).
Michael stated in #579 that the values from the database where
```
["rel_type"] => string(0) ""
["milestone_id"] => string(12) "No Milestone"
```
This fixes that by specifying a default value of 0 for both fields (which isn't a possible relation for the 2 fields). If this value is met then in the model they are set to null (note I don't know whether these checks for 0 are better done in model or table - I was strongly tempted to put them into App\Tracker\Table\IssuesTable::check() function tbh)
Note I have absolutely no virtual box for this thing set up so you MUST test this before merging
> Fix bug in latest filter package. Fixes #579

- templates/tracker/issue.add.twig
This PR fix a issue that i introduced here: https://github.com/joomla/jissues/pull/554
So the help text is shown also if no categories are defined see here: http://issues.joomla.org/tracker/weblinks/add
> Fix issue with help text for categories

- cli/Application/Command/Get/Project/Issues.php
- templates/tracker/issue.index.twig
This will prevent a PHP notice in our CLI script when the repo/branch had been deleted by the user.
> Fix a notice when the repository has been deleted

- src/App/Tracker/Controller/Issue/Submit.php
> Add "No code attached yet" label for CMS issues. Fix #590.

- src/App/Tracker/Model/IssueModel.php
- templates/tracker/issue.index.twig
- templates/tracker/issues.index.twig
So I've changed the behavior a little bit :wink: If a user is found in the tracker users then link to his tracker profile. If not found then link to his GitHub page.
Ref #652 @roland-d
> Make username linkable to GitHub page. Close #652

- cli/Application/Command/Get/Project/Issues.php
- src/App/Tracker/Controller/Hooks/ReceiveIssuesHook.php
- src/App/Tracker/Controller/Hooks/ReceivePullsHook.php
This PR will set the build to branch default:
1. On initial sync of the issue.
2. On hooks if the build is empty.
This is required because we require the build when issue is created on the tracker.
> Set build to branch default in hooks and sync

- src/App/Tracker/Controller/Hooks/ReceivePullsHook.php
Ref #647. Th problem was in `insertid()` that was returning the incorrect id, because last insert is going to activities table. This PR should fix it as it uses `issue_id` from the issue model state.
> Fix  incorrect last added issue id. Close #647

- templates/editor.twig
This makes the tabs look *different* on small screens.
e.g.:
As I am not the design guy I'd like you to review this please :wink: 
P.S.: Oh and there is a hard link to http://issues.joomla.org - while currently there is nothing wrong, maybe we should use `{{ uri.base.path }}` here to make it more portable?
> Fix editor tabs in mobile view

- composer.json
- etc/config.dist.json
- src/JTracker/Authentication/GitHub/GitHubLoginHelper.php
Hello again :wink: 
I recently had to setup my environment on a new computer and I ran into some installation problems, so this PR tries to fix this for new installs (exising install should not be affected so this should be full B/C :tongue:)
1. php-curl is not installed<br />
In this case `HttpFactory::getAvailableDriver()` returns `false`. We miss a check in our `GitHubLoginHelper` here so the next call will produce a fatal error.<br />
I also added the CURL extension as a dependency to our `composer.json` file so the application wouldn't even install if  CURL is not available.
2. The log path is not available<br />
This might have changed in recent Apache versions, not sure. It is required to use a full path in the config file for the log path setting as a relative path would not work …
> Fix some possible setup errors

- src/App/Tracker/Controller/Hooks/Listeners/AbstractListener.php
- src/App/Tracker/Controller/Hooks/Listeners/JoomlacmsCommentsListener.php
- src/App/Tracker/Controller/Hooks/Listeners/JoomlacmsIssuesListener.php
- src/App/Tracker/Controller/Hooks/Listeners/JoomlacmsPullsListener.php
- src/App/Tracker/Controller/Hooks/ReceiveCommentsHook.php
This PR try to implement the RTC Label Check to run also if a comment was add.
- add a pull
- set status to RTC
- comment (using jissues)
- make sure the RTC label will add.
- add a new pull
- set the status to RTC
- comment (using github)
- make sure the RTC label will add.
I can't realy test it as i have no testserver setup. But in theory it should work or i miss something?
So it is not 100% idial but we have a bit more `automagic` in the Tracker.
> Let the RTC Label Check also run on a comment

- src/App/Tracker/Controller/Hooks/Listeners/JoomlacmsPullsListener.php
This PR implement a check for the unit / system test label that gets added if we change a file in the `tests` folder or the `.travis.yml`, `phpunit.xml.dist` or `travisci-phpunit.xml`.
> Add the unit / system test label if we change the tests folder

- src/JTracker/Application.php
Fixes an issue when items are accessed directly by URI.
Root cause is the bad design of our User object that is [badly coupled to the Project](https://github.com/joomla/jissues/blob/master/src/JTracker/Authentication/User.php#L124) (blame @elkuku on this..)
You may verify that the bug exists by sailing to http://issues.joomla.org/tracker/jtests/44
**Expected**: Issue 44 on the test project opens.
**Actual**: Issue 44 on the CMS project opens.
After applying the patch this should be fixed (hopefully).
> Load language files after routing is processed.

- src/App/Groups/Controller/Groups.php
- src/App/Projects/ProjectAwareTrait.php
- src/App/Tracker/Controller/AbstractHookController.php
- src/App/Tracker/Model/IssuesModel.php
- src/App/Tracker/View/Categories/CategoriesHtmlView.php
- src/App/Tracker/View/Category/CategoryHtmlView.php
- src/App/Tracker/View/Issue/IssueHtmlView.php
- src/App/Tracker/View/Issues/IssuesHtmlView.php
- src/App/Users/Model/UserModel.php
- src/JTracker/Authentication/User.php
- src/JTracker/Model/AbstractTrackerDatabaseModel.php
- src/JTracker/View/AbstractTrackerHtmlView.php
This PR adds a trait for classes which have a `TrackerProject` object injected into them to help cut back on some of the code duplication in repeating a `$project` class var and `getProject()` and `setProject()` methods.
> Implement a ProjectAwareTrait

- src/JTracker/Service/ConfigurationProvider.php
This will replace environment variables from the system in the configuration.
It is used in the openshift branch like this: https://github.com/joomla/jissues/blob/openshift/etc/config.openshift.json
(see also: [jissues/openshift/docs#environment-variables](https://github.com/joomla/jissues/blob/openshift/Documentation/Development/Openshift.md#environment-variables))
But I think this might be useful also for other environments.
> Add Replace environment variables in configuration

- src/App/Tracker/Controller/Hooks/Listeners/AbstractListener.php
- src/App/Tracker/Controller/Hooks/Listeners/JoomlacmsTestsListener.php
- src/App/Tracker/Controller/TestResult/Ajax/Alter.php
- src/App/Tracker/Controller/TestResult/Ajax/Submit.php
This will add an `onTestAfterSubmit` event and a `JoomlacmsTestsListener` event listener that will create a status on GitHub whenever a test is submitted (or altered) on jissues.
FYI GitHub statuses are those annoying messages that appear for "external services" like Travis.
In our case this would reflect the test results (from JBS) to the GitHub UI along with the Travis (or other) test results.
Example:
The text that appears is fully customizable for every project and  I would beg you to postpone discussions about the wording after and only if this PR has been merged - thanks :wink: 
Depends on #694, closes #596
> JoomlacmsTestsListener

- src/App/Tracker/Controller/Hooks/Listeners/JoomlacmsPullsListener.php
This just replaces `soon` with `within 4 weeks` on the `Test instructions missing` Message.
The 4 weeks are also in the default textes for PBF events (can be found here: http://br.joomlapbf.com/). Thanks for the tip @roland-d
> Add the 4 weeks to the no desc message

- templates/tracker/issue.index.twig
This happens if we have a normal PR without any votes and not logged in.
After this patch the div should not be there ;)
> Remove the unneded div if we have nothing to show

- src/App/Tracker/Controller/Issue/Save.php
- templates/tracker/issue.add.twig
- templates/tracker/issue.edit.twig
Some days bevor i was thinking PLT acion is `admin` but since i'm in the same Group as the other PLT Memebers i notice the they have the action `manage` and the `admin` is something more higher. ;)
But i guess we can allow the using of labels and milestones to the PLT and me as well until they don't decide different. :)
> Lets PLT / Manager use Milestones and Labels from issues.joomla.org ;)

- cli/Application/Command/Get/Project/Issues.php
- src/App/Tracker/Controller/Hooks/ReceivePullsHook.php
- src/JTracker/Github/DataType/Commit/CombinedStatus.php
- src/JTracker/Github/Github.php
- src/JTracker/Github/Package/Repositories.php
- src/JTracker/Github/Package/Repositories/Statuses.php
- src/JTracker/Helper/GitHubHelper.php
- templates/tracker/issue.index.twig
Pull Request for Issue # .
Some time ago GitHub introduced the [Combined Status API](https://developer.github.com/changes/2014-03-27-combined-status-api/)([API](https://developer.github.com/v3/repos/statuses/#get-the-combined-status-for-a-specific-ref))
Currently we display only the last status in the item view (and its state in the list view)
* Importing statuses has been added (and tested) on CLI import.
* Importing statuses has been added (and **NOT** tested) on Hooks import.
Merge, push, wait until PRs are updated or run the `get project` command with the `-f` option on the server.
> GitHub statuses

- src/App/Tracker/Controller/AbstractHookController.php
- src/App/Tracker/Controller/Hooks/ReceivePullsHook.php
Pull request webhooks are setting some merge state data which we can use to track statuses better in the application.  This PR will check if a pull request gets closed and is merged (looks like it applies to the big green button only, I need to find something merged manually) and if so we'll set the closed status to "Fixed in Code Base" instead of the generic "Closed".  We'll also add a merge activity for the person who merged the item (though it looks like this happens already but I can't trace down what's adding it).
Review changes and compare them against the pull request webhook data (https://github.com/joomla/jissues/settings/hooks/1060432 has a log of them for repo admins).  Throw this patch on a server that can receive hooks, close a PR on a project the app supports, and validate …
> Catch when pull requests are merged and set state accordingly

- src/App/Debug/TrackerDebugger.php
- src/App/Tracker/Controller/AbstractHookController.php
- src/App/Tracker/Controller/Hooks/Listeners/AbstractListener.php
- src/App/Tracker/Controller/Hooks/Listeners/JoomlacmsPullsListener.php
- src/App/Tracker/Controller/Hooks/ReceiveCommentsHook.php
- src/App/Tracker/Controller/Hooks/ReceiveIssuesHook.php
- src/App/Tracker/Controller/Hooks/ReceivePullsHook.php
- src/App/Tracker/Controller/Issue/Save.php
- src/App/Tracker/Controller/Issue/Submit.php
- src/JTracker/Application.php
- src/JTracker/Controller/AbstractAjaxController.php
PSR-3 defines a standard for how Exceptions should be logged by attaching it to the context array of a log message.  Monolog supports this structure.  So, all places where Exceptions are being logged now attach the Exception to the context array (in the case of Monolog, the full Exception's data (type, message, code, and trace) get attached to log messages which actually makes these a bit more useful now.
Also changed a couple of places to chain Exceptions where there was a new Exception being thrown.
Trigger an error, validate Exception data is logged.  Or read the code and make sure I didn't screw this up.
> Log Exceptions per PSR-3 standard

- cli/Application/Application.php
- src/App/Debug/DebugApp.php
- src/App/GitHub/GitHubApp.php
- src/App/Groups/GroupsApp.php
- src/App/Projects/ProjectsApp.php
- src/App/Support/SupportApp.php
- src/App/System/SystemApp.php
- src/App/Text/TextApp.php
- src/App/Tracker/TrackerApp.php
- src/App/Users/UsersApp.php
- src/JTracker/AppInterface.php
- src/JTracker/Application.php
- src/JTracker/ApplicationTrait.php
This creates an `AppInterface` and base app classes for each of the apps in the overall application.  Compare this to a really simplified version of Symfony bundles.  Long and short it allows each app to load its services into the application structure.  The loading of routes for the router is moved into this layer instead of directly in the application class now.
This layer should be used to help be able to create a more service injection based approach to things versus a service locator approach that's used now.  It also sets up a way to be able to set up the command line environment to be able to use the apps' APIs the same way the web app does.
Everything still works.
> App services layer

- src/JTracker/Upload/File.php
Pull Request for Issue #760.
This will skip `txt` files mime validation.
Use my [testing server](http://jtracker.j4devs.ru/tracker/jissues-test/) and try to upload Joomla's system info file. It should upload fine.
> Skip mime validation for txt files

- src/JTracker/Application.php
- src/JTracker/View/Renderer/TrackerExtension.php
Fix #806
**Bug**: The `users language` parameter (if set) overrides the `session language` parameter (if set) causing the current language to be "resetted" to the users parameter language.
This happens if the following criteria are met:
1. You are logged in.
1. You have set a language in you user settings (in jissues)
1. This language is different from the one you are selecting using the language selector.
The Application class now has a method to get the current language tag.
Now the language code present in the session (if so) is preferred over the user parameter. I **guess** that this should be the right behaviour.
**Note**: While I completely dislike adding even more code to the Application class, I swear that I will move the `loadLanguage()` method to the `LanguageHelper` class …
> Session language

- www/media/css/jtracker.css
For screen up to 767px, the display of the icon search and clear button are incorrect, creating an horizontal scrolling.
> Fix for the RWD of users search

- src/App/Users/Controller/User/Refresh.php
- src/JTracker/Authentication/GitHub/GitHubLoginHelper.php
Refresh user's name
Before it was not possible to refresh the user's name from Github.
After it will be possible to refresh the user's name
> Refresh User's name and sync with Github profile

- cli/Application/Command/Export/Langfiles.php
- cli/Application/Command/Get/Languagefiles.php
- cli/Application/Command/Get/Project.php
- cli/Application/Command/Make/Depfile.php
- composer.json
- composer.lock
- src/JTracker/View/Renderer/TrackerExtension.php
- templates/footerMenu.twig
- templates/tracker/issue.add.twig
Here are some changes required to use named parameters in translation strings, supported as of version 2.5 of the g11n library.
<del>For some unknown reason (to me) the tag/release does not appear on [Packagist](https://packagist.org/packages/elkuku/g11n) so I used `dev-master` in the composer file.</del>PEBKAC
Write lots of translatable strings with named parameters :wink:
> G11n named parameters

- templates/trackerMenu.twig
The about us menu item on the /etc menu is not really about us (people) but just about (code or project)
> Update menu title

- src/JTracker/Helper/LanguageHelper.php
- src/JTracker/View/Renderer/TrackerExtension.php
- templates/index.twig
Pull Request for Issue #852  .
This will add initial support for "RTL" languages.
Add a new key to one of the existing languages defined in the [LanguageHelper](https://github.com/joomla/jissues/blob/master/src/JTracker/Helper/LanguageHelper.php#L45) class
'direction' => 'rtl'
Or add a proper RTL language and set the key as shown.
Further improvements depends on input from a native speaker or someone with more knowledge than me on the subject.
> Add initial support for "RTL" languages

- src/App/Tracker/Controller/Issue/Submit.php
Pull Request for Issue #862  .
In the submit controler we call the save method wihout the indexes `new_state` and `old_state` while this is expected the save method try to check on that field so we should fake it here.
Sumbit a item via the Tracker.
Check the logs
```
Undefined index: new_state in src/App/Tracker/Model/IssueModel.php on line 503
Undefined index: old_state in src/App/Tracker/Model/IssueModel.php on line 504
```
test againg with the patch.
Maybe we should move the check to the model?
so we have here: https://github.com/joomla/jissues/blob/master/src/App/Tracker/Model/IssueModel.php#L503-L504 something like:
```
// Assume open if nothing is set
$src['old_state'] = isset($src['old_state']) ? $src['old_state'] : 'open';	
$state = isset($src['new_state']) ? $src['new_state'] : …
```
> Fix: Notices in logs #862

- src/App/Tracker/Controller/Hooks/Listeners/JoomlacmsPullsListener.php
- src/App/Tracker/Controller/Hooks/ReceiveIssuesHook.php
- src/App/Tracker/Controller/Hooks/ReceivePullsHook.php
- templates/tracker/issue.index.twig
Pull Request for Issue #904.
Restructured the issues and pull requests webhook receivers:
- When inserting new records, we will only do so for `opened`, `closed`, and `reopened` events; we have had funky issues with race conditions when processing other event types as the initial one inserting the data
- When updating existing records, there are now different paths based on the action
- `opened`, `closed`, `reopened`, `edited`, and `synchronize` (for pull requests) continue to behave as before
- `labeled` and `unlabeled` events will now only update the item's labels versus trying to update all data
- Other event types will hit a default case and report as unsupported (this includes `milestoned` and `unmilestoned`, there is no logic for updating milestones implemented into our webhook code …
> Refactor webhooks (Fix #904)

- src/App/Tracker/Controller/Hooks/Listeners/JoomlacmsPullsListener.php
- tests/tracker/Hooks/Listeners/JoomlaCmsPullsListenerCheckFilesAndAssignCategoryTest.php
Pull Request for Issue https://github.com/joomla/joomla-cms/pull/13461#issuecomment-270239402
Add the folder media/system/js/fields/calendar-locales to the TT handled folders.
A change or a new file in that folder should add the language change label
> add path media/system/js/fields/calendar-locales to the TT handled folders

- composer.json
- composer.lock
It was brought to my attention that Crowdin is going to change its API URL and that the old one will be "competely disabled " on July 25th (2017, I suppose...)
See: https://github.com/elkuku/crowdin-api/pull/1
I do not have any active project and my trial account has expired long ago so - please test :wink:
> Update Crowdin api lib

- cli/Application/Command/Test/Hook.php
- src/App/Tracker/Controller/AbstractHookController.php
- src/JTracker/Controller/AbstractTrackerController.php
Fixes a few issues when using the test hook functionality
1. Project ID is an integer not string
2. Running the cli from the bin folder isn't supported
3. We call `getProject` on the `app` property - however this is the cli application which doesn't have the function. In this case we need to explicitly get the WebApplication which contains that method (Would it be better to have an TrackerApplicationInterface which contains this method with a trait that has this method in both apps have available?)
> Fix using test hook

- src/JTracker/Authentication/Database/TableUsers.php
```
1364 Joomla\Database\Exception\ExecutionFailureException
Field 'params' doesn't have a default value
exception: Joomla\Database\Exception\ExecutionFailureException: Field 'params' doesn't have a default value in ROOT/vendor/joomla/database/src/Mysqli/MysqliDriver.php:683
Stack trace:
#0 ROOT/vendor/joomla/database/src/DatabaseDriver.php(1046): Joomla\Database\Mysqli\MysqliDriver->execute()
#1 ROOT/src/JTracker/Database/AbstractDatabaseTable.php(418): Joomla\Database\DatabaseDriver->insertObject('#__users', Object(stdClass), 'id')
#2 ROOT/src/JTracker/Database/AbstractDatabaseTable.php(174): JTracker\Database\AbstractDatabaseTable->store()
#3 ROOT/src/JTracker/Authentication/User.php(169): JTracker\Database\AbstractDatabaseTable->save(Object(JTracker\Authentication\GitHub\GitHubUser)) …
```
> Fix saving users on MySQL 5.7

- cli/Application/Command/Test/Hook.php
- etc/migrations/20170723001.sql
- etc/mysql.sql
- src/App/Tracker/Controller/Hooks/ReceivePullReviewHook.php
- src/App/Tracker/Table/ReviewsTable.php
- src/App/Tracker/routes.json
Pull Request for Issue #885  .
Some work on receiving the webhook for pull request reviews. I'm deliberately leaving doing the UI for this as a separate PR, so we can at least be storing the data whilst we are working on the interface
1. Test it on a live service - I haven't figured out fully integrating this yet
2. I'm unsure if we get a hook on the COMMENT state documented in the API (https://developer.github.com/v3/pulls/reviews/#submit-a-pull-request-review) or not
3. Do we want to save in the activities table who modified a review?
4. In the case of dismissing a comment from the docs alone I couldn't work out where the associated dismissed message was stored (if it is)
5. I wasn't sure whether the comments need to be stored as text rather than a `varchar(500)`
> Add WIP on recieving webhooks for pull request reviews

- src/App/Tracker/Controller/Hooks/ReceivePullReviewHook.php
GitHub hook doesn't give us the info we need. So just add a TODO for a rainy day
> Don't store dismissal info

- src/App/Tracker/Controller/Hooks/ReceiveCommentsHook.php
- src/App/Tracker/Controller/Hooks/ReceivePullReviewHook.php
I can't test this because despite https://github.com/joomla/jissues/compare/fix/dismissed?expand=1#diff-7556531a1ad8f82503521b2e86695d92R363
I get
```
[2018-02-18 21:50:20] JTracker.ERROR: Database query failed (error #1364): Field 'labels' doesn't have a default value; Failed query: INSERT INTO `jos_issues` (`issue_number`,`project_id`,`title`,`description`,`description_raw`,`status`,`opened_date`,`opened_by`,`modified_date`,`modified_by`,`pr_head_user`,`pr_head_ref`,`pr_head_sha`,`build`) VALUES  ('19717','1','[4.0] Airbnb ECMAScript 2017 (ES6) Coding Standards for the files in directory build/build-modules-js','<body_text_removed_for_github>','1','2018-02-18 12:06:19','astridx','2018-02-18 21:05:39','dgt41','astridx','j4_airbnb/es6/codingstandards','a5e1ac26547c70cecdaecdbfbd7c9cb94542e …
```
> Create an issue if one doesn't exist

- src/App/Tracker/Controller/Hooks/ReceivePullReviewHook.php
Search by the Review Number because more than one person can submit a review, and you can review after each commit
I'm leaving the `issue_project_index` in place so we can use it for getting all reviews for an issue
> GitHub allows more than one person to submit a review multiple times

- src/App/Tracker/Controller/Hooks/Listeners/JoomlacmsPullsListener.php
Pull Request for Issue #1030 
Add the new components csp and workflow to the auto detection
Before this patch i have created the com_csp & com_workflow category in the tracker application. Do we need to include that somewhere in the repo too?
Create a patch that changes com_csp or com_workflow
The tracker now adds the categories
> Add the new components csp and workflow

- cli/Application/Command/Test/Checkstyle.php
- composer.lock
Update to new version of sniffer removing the allowed failures
> Remove phpcs exceptions

- src/App/Tracker/Controller/Hooks/Listeners/JoomlacmsIssuesListener.php
- src/App/Tracker/Controller/Hooks/Listeners/JoomlacmsPullsListener.php
Change `Request for Comment` to `RFC` to consolidate redundant labels.
> Change RFC label

- src/App/Tracker/Controller/Issue/Save.php
- templates/tracker/issue.add.twig
- templates/tracker/issue.edit.twig
Pull Request for Issue https://github.com/joomla/joomla-cms/pull/25233
Allow the jbs group to see and change the labels and milestones using the bot
After this change the groups with edit permission can change the labels and milestones. Before only admins could have done that.
> Allow the jbs group to see and change the labels and milestones using the bot

- package.json
The spdx have deprecated the short license identifier GPL-2.0+ and we should use GPL-2.0-or-later
https://spdx.org/licenses/
Pull Request for Issue # .
> Update deprecated licence

- src/JTracker/Application.php
Pull Request for Issue #1057 (but doesn't fix it - just improves transparency) .
https://github.com/joomla/jissues/blob/865ed587df9c9bc5f2616d93ef753b71e5fd935c/src/App/Projects/Model/ProjectModel.php#L76 currently throws an exception - making the one thrown here and case that can never exist.
Code Review
> Remove exception and document correct one
