- cli/Application/Command/Get/Project/Comments.php
This will fix the issue when comments deleted on GitHub are not deleted on tracker. Ref #586
> Add deleting of comments that was deleted on GitHub. Ref #586

- composer.json
- composer.lock
- src/App/Tracker/Model/IssueModel.php
- src/App/Tracker/Table/IssuesTable.php
So let's move those normalization to the table class as requested by @b2z - we should have done that earlier  I guess...
> Normalize some table fields Ref #581 Fix #606

- src/App/Tracker/Controller/Issue/Save.php
- src/App/Tracker/Model/IssueModel.php
- src/App/Tracker/Table/IssuesTable.php
I believe that this might solve several issues we have currently including #607, #611, #617 and maybe others...
I started thinking about it here: https://github.com/joomla/jissues/pull/595#issuecomment-70272396
> Ensure that modified date is always set from GitHub

- src/App/Tracker/Table/IssuesTable.php
I believe that his code is not used anymore, but I might be wrong...
> Remove unused code

- src/App/Users/Controller/User/Refresh.php
- src/JTracker/Authentication/GitHub/GitHubLoginHelper.php
> Add the email refresh for a user. Fix #558.

- bower.json
- templates/index.twig
- templates/lang-switcher.twig
- www/jtracker/core/css/jtracker.css
See #582 for reference. [Live demo](http://jtracker.j4devs.ru/) is available on my test server.
> Redesign language switcher

- src/App/Tracker/Controller/Hooks/Listeners/JoomlacmsPullsListener.php
This should add a "Language Change" label to pull requests on the CMS repo.
> Add language label to PRs (Fix #591)

- src/App/Tracker/Controller/AbstractHookController.php
- src/App/Tracker/Controller/Comment/Ajax/Submit.php
- src/App/Tracker/Controller/Hooks/ReceiveCommentsHook.php
- src/App/Tracker/Controller/Hooks/ReceiveIssuesHook.php
- src/App/Tracker/Controller/Hooks/ReceivePullsHook.php
Still a work in progress, this branch will have the web hooks updated to insert data to the database via model classes versus the table classes.
> Use models in web hooks

- etc/mysql.sql
- Adds unique index to the `#__issues` table on issue number and project ID
- Adds cascade operations to the `#__issue_category_map` table's foreign key to the `#__issues` table
> Database schema changes

- cli/Application/Command/Get/Project/Events.php
- src/JTracker/Service/DatabaseProvider.php
> Exclude labeled/unlabeled events from sync. Close #655

- src/App/Tracker/Controller/AbstractHookController.php
This reverts the check that was added for debugging here: https://github.com/joomla/jissues/issues/670 or should this a long term logging point?
> Revert Check for  testing #670

- src/App/Tracker/Controller/Hooks/ReceivePullsHook.php
- src/JTracker/Controller/AbstractAjaxController.php
Part of the fix to #681 
Note if there is an exception now when performing the hook action we no longer close the application at that point but return an error message an appropriate status header
> Send back error message and status code if there's an error in the pulls Hook

- src/JTracker/Controller/AbstractAjaxController.php
since: https://github.com/joomla/jissues/pull/682/files
> Fix `@since` doc block comment.

- src/App/Tracker/Model/IssuesModel.php
- templates/tracker/issues.index.twig
> Add an "all" filter - Fixes #672

- src/App/Tracker/Controller/Hooks/Listeners/TestsItemsListener.php
- src/App/Tracker/Controller/Hooks/Listeners/TestsTestsListener.php
The event listeners I used for testing.
Depends on #694.
> Add test project event listeners

- src/App/Tracker/Controller/DefaultController.php
- src/App/Tracker/Controller/Issue/Ajax/Listing.php
- src/App/Tracker/Model/IssuesModel.php
- templates/tracker/issues.index.twig
- templates/tracker/tracker.filters.twig
This will add a "type" filter:
Ref.: #702
> Add a "type" filter

- src/App/Tracker/Controller/TestResult/Ajax/Submit.php
This add a clean line between the automatic comment and the user comment on submitting a test result. ;)
> Add a clean line between the automatic comment and the user Comment

- src/App/Tracker/Controller/Hooks/Listeners/JoomlacmsPullsListener.php
This PR set the status back to pendig if the PR gets closed and reopened again
> Set the status to pendig if the PR gets closed and reopened again

- src/App/Tracker/Controller/DefaultController.php
- src/App/Tracker/Controller/Issue/Ajax/Listing.php
- src/App/Tracker/Model/IssuesModel.php
- templates/tracker/issues.index.twig
- templates/tracker/tracker.filters.twig
This PR will add "No" option for easy test filter as requested in #719. Also it will fix incorrect state filter for "Permalink" button.
Tests are welcomed :)
http://jissues.j4devs.ru/tracker/jissues-test
> "No" option for easy test filter. Close #719

- src/App/Tracker/Controller/Issue/Add.php
Pull Request for Issue #748
This is another approach - less intrusive...
> Add support for project specific issue templates - Fix #748

- etc/config.dist.json
- src/App/Tracker/Controller/Upload/Ajax/Put.php
- templates/uploader.full.twig
- www/jtracker/core/js/uploader-img.js
Pull Request for Issue #744 .
Proceed to [my test server](http://jtracker.j4devs.ru/tracker/jissues-test) and try to upload supported file types.
> Add support for new file types. Fix #744

- src/App/Activity/Controller/Ajax/ProjectActivity.php
- src/App/Activity/Controller/Ajax/TotalActivity.php
- src/App/Activity/Model/TotaluseractivityModel.php
- src/App/Activity/Model/UseractivityModel.php
This shoud fix travis here: https://travis-ci.org/joomla/jissues/jobs/118553441 for this PR: https://github.com/joomla/jissues/pull/491
> Fix codestyle / travis activity chart PR

- Documentation/Development/Database-Migrations.md
- Documentation/Development/Directory-Structure.md
- cli/Application/Command/Database/Database.php
- cli/Application/Command/Database/Migrate.php
- cli/Application/Command/Database/Status.php
- etc/migrations/20160611001.sql
- etc/mysql.sql
- src/JTracker/Database/Migrations.php
- src/JTracker/Service/DatabaseProvider.php
Creates an API to be able to migrate the database when changes are applied to the base schema.
For now this is mostly review/critique since there aren't any migrations to test with.  The API is explained in the Documentation file that's added to try and make it clear how it all works.
> Create a database migrations API

- templates/github/labels.index.twig
:gb: Small typo fix to appear as en-GB version
Easy test on code review
> :gb: Small typo fix

- cli/Application/Command/Make/Composergraph.php
- src/App/Tracker/Table/CategoryTable.php
- src/App/Tracker/Table/IssueCategoryMappingTable.php
- src/App/Users/Controller/User/Edit.php
- src/App/Users/Controller/User/Refresh.php
- src/App/Users/Controller/User/Save.php
- templates/tracker/categories.index.twig
- templates/tracker/category.add.twig
- templates/tracker/category.edit.twig
:us: to :uk: for source language + consistency
Easy fix on code review
Thanks
> :us: to :uk: for source language + consistency

- cli/Application/Command/Install/Install.php
- templates/groups/groups.index.twig
:uk: Typos - easy fix
On code review.
Thanks
> :uk: Typos - easy fix

- templates/groups/group.edit.twig
- templates/projects/projects.index.twig
- templates/support/markdown.index.twig
- templates/tracker/categories.index.twig
- templates/tracker/tracker.filters.twig
Consistency details
Easy fix on code review
Thanks
> Consistency details

- cli/Application/Command/Get/Project/Events.php
- cli/Application/Command/Get/Project/Issues.php
- cli/Application/Command/Help/Help.php
- cli/Application/Command/Make/Languageflags.php
- cli/Application/Command/Test/Langfiles.php
- src/App/Debug/Controller/Logs.php
- src/JTracker/Github/Package/Issues.php
So there are several unused use statements which my first class IDE was unable to spot :( 
I was testing the SensioLabs thingy which gave me the following result: https://insight.sensiolabs.com/projects/1a93532b-bc3d-4b14-bc94-1189581b42a7/analyses/4
I think there are several things worth looking at e.g. `Boolean should be compared strictly` (70) - they say that this will improve performance..
Good thing is that it will only take 9.7 weeks to fix all "errors" - so they say :tongue:
> Code review

- templates/tracker/issue.index.twig
Thank you to check if it is done the way it should + I guess I miss something: any .po file to change?
Thanks
> Make the pagination "Older" "Never" available for t9n

- templates/projects/projects.index.twig
Simple fix
Improve readability
**BEFORE**
**AFTER**
> improve readability

- www/media/css/jtracker.css
> Fix for the state buttons width for mobile device

- credits.json
Crowdin added + :uk: fix
On code review
> Crowdin added + :uk: fix

- cli/Application/Command/Get/Users.php
Added CLI app to update user information
Use this command to get and update all the user's info.
```bash
cli/tracker.php get users
```
> [cli] Add new command to get and set user name

- cli/Application/Command/Get/Project/Issues.php
It contains enhancement in CLI app.
> Adding option to fetch issue based on status

- cli/Application/Command/Get/Project/Issues.php
:uk: Typo fix
on code review - thanks
> :uk: Typo fix

- cli/tracker.php
Fix travis from  https://github.com/joomla/jissues/pull/812#issuecomment-232957489
> fix travis

- src/App/Debug/TrackerDebugger.php
This is meant as another aid to further debug #834
> Add request parameters to debug information

- Documentation/Internationalisation/Crowdin.md
Pull Request for Issue #825 
Feel free to add more content and correct my Franglish.
> Creation of Crowdin Page.

- src/App/Tracker/Controller/Hooks/Listeners/JoomlacmsPullsListener.php
Add auto category for JS changes
Change a JS file (.js) => the JavaScript category should be added by the Tracker :smile:
> Add auto category feature for the JavaScript category

- src/JTracker/Application.php
- src/JTracker/Controller/AbstractTrackerController.php
This will add some messages about the loaded MVC classes to the profiler output.
This might not be the best place to show this information, but it was easy to hack in :wink: 
Turn on debugging and have a look a the profiler output.
> Add more info to the profiler output

- templates/tracker/issues.index.twig
- templates/tracker/tpl/filters.twig
- templates/tracker/tracker.filters.twig
Capitalise some labels for consistency
> Capitalise

- composer.json
- composer.lock
- src/App/Debug/Controller/Monologs.php
- src/App/Debug/Renderer/Html.php
- src/App/Debug/TrackerDebugger.php
- src/App/Debug/View/Logs/LogsHtmlView.php
- src/App/Debug/View/Monologs/MonologsHtmlView.php
- src/App/Debug/routes.json
- src/JTracker/Application.php
- src/JTracker/Controller/AbstractTrackerController.php
- templates/debug/logfields.twig
- templates/debug/monologs.index.twig
- templates/trackerMenu.twig
- www/media/css/jtracker.css
* Move HTML stuff from the debugger to a dedicated class (still looks like hell...)
* Parse the log files generated by Monolog (all but the PHP log), and display them in a more eye friendly manner.
* Check that debugging still works and everything shows as before.
* Check that log file display has been improved - suggestions welcome.
**Note** I tested with my local files as well as the files available to me on the server. I noted that the server files are not quite up to date and some are really huge (e,g, the `cron.log` counts > 50mb)...
**Before**
**After**
> Debugging and Logging improvements

- src/App/Tracker/Controller/Hooks/Listeners/JoomlacmsPullsListener.php
Remove the 2.5.x branch check as there is no 2.5.x branch anymore: https://github.com/joomla/joomla-cms/branches
Check the bot is still working.
> Remove the 2.5.x branch check as there is no 2.5.x branch anymore

- cli/Application/Command/Test/Phploc.php
- src/App/Debug/Format/Html/LinkFormat.php
Pull Request for Issue # .
fix warnings form the IDE
review
> fix warnings form the IDE

- src/App/Tracker/Controller/Hooks/Listeners/JoomlacmsPullsListener.php
There is also a frontend part of com_seach add it here.
review
> There is also a frontend part of com_seach

- Vagrantfile
- build/puppet/files/etc/dotdeb.list
- build/puppet/files/etc/suryphp.list
- build/puppet/manifests/default.pp
Pull Request for Issue #987.
```
vagrant@contrib-jessie:~$ php -v
PHP 7.1.9-1+0~20170902060604.8+jessie~1.gbpebe5d6 (cli) (built: Sep  2 2017 06:21:43) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
with Zend OPcache v7.1.9-1+0~20170902060604.8+jessie~1.gbpebe5d6, Copyright (c) 1999-2017, by Zend Technologies
with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans
```
You will need to destroy your current virtual machine and create a new one by running `vagrant up`.
> Update PHP package source. Close #987

- src/App/Tracker/Controller/Hooks/Listeners/JoomlacmsIssuesListener.php
- src/App/Tracker/Controller/Hooks/Listeners/JoomlacmsPullsListener.php
Pull Request for Issue #1002
New Auto Label Rule for RFC
- Create a issue with the title containing `[RFC]`
- see that the rfc label is added.
> New Auto Label Rule for RFC

- www/.htaccess
With this PR we set the basic http security headers
> Implement the first httpheader for the issue tracker

- src/JTracker/View/Renderer/TrackerExtension.php
Pull Request for Issue code was unnecessarily multiline
Reduce code to a single line
Code review should be sufficient.
> Convert multiline code to single line

- cli/Application/Command/Test/Hook.php
- src/App/Tracker/Controller/Hooks/ReceivePullReviewHook.php
- src/App/Tracker/Table/ReviewsTable.php
- Fix review when someone comments without explicit approval.
- Fixes doc comments for the review states
- Outputs the json result from the controller when you test a hook
> Fix for commented state

- src/App/Tracker/Controller/Hooks/ReceivePullReviewHook.php
- Fix database column for the issue id
- It's called pull_request not edit - that will teach me to copy/paste
> Fix edit logic

- src/App/Tracker/Controller/Hooks/ReceivePullReviewHook.php
If a review doesn't exist in the database (easily possible because we aren't importing old reviews), then create it
> Create a review if it doesn't exist

- www/.htaccess
> [CSP] Only run this .htaccess rules on the live site

- templates/tracker/issues.index.twig
> index page table a11y

- src/App/Activity/Model/UseractivityModel.php
> Only allow preset periods

- src/App/Debug/Renderer/Html.php
- src/App/Debug/TrackerDebugger.php
Fix #1045 
Fix language debug
Check language debug
> Fix language debug

- package-lock.json
Updates terser webpack dep from 1.4.1 to 1.4.3 which patches through some fixes
> Update terser webpack from 1.4.1 to 1.4.3

- src/JTracker/Application.php
Pull Request for Issue https://github.com/joomla/jissues/issues/1057 .
Work around for a circular dependency in the error handler when displaying the error page for a project that does not exist. It's not the cleanest thing ever but should do the job.
Navigate to a project that doesn't exist. Before patch the emergency fallback error handler. After patch a nice happy one
> Use default application to work around error page edge case

- etc/migrations/20200310001.sql
- etc/mysql.sql
- src/App/Tracker/Controller/Hooks/ReceivePullsHook.php
- src/App/Tracker/Model/IssueModel.php
Pull Request for Issue https://github.com/joomla/jissues/issues/1052 .
First draft of changes required for draft PRs
Check DB. We can also choose to grab an initial dump of the PRs that are currently in draft so they can be populated correctly for the CMS as a manual extra.
> Store Draft PR status to database

- src/App/Tracker/Model/IssuesModel.php
- templates/tracker/issue.index.twig
- templates/tracker/issues.index.twig
Pull Request for Issue https://github.com/joomla/jissues/issues/1052 .
Adds a badge in the item view that marks a PR as a draft
Check if a draft shows as such in the UI
> Show Draft PRs in UI

- src/App/Tracker/Controller/Hooks/Listeners/JoomlacmsPullsListener.php
- tests/tracker/Hooks/Listeners/JoomlaCmsPullsListenerCheckFilesAndAssignCategoryTest.php
Pull Request for Issue # .
Add NPM label on SCSS changes
Create a PR modifying admin, site or installation template SCSS.
NPM label added.
NPM label not added.
> Add NPM label on SCSS changes

- composer.lock
Update joomla/github package needed for git token change
> Update github package

- src/App/Groups/View/Group/GroupHtmlView.php
Pull Request for Issue #1112 .
Bit of a bodge for the javascript error when editing groups.
Check you can edit groups
> Fix group editing with a bodge

- templates/index.twig
Pingdom hasn't been used for a long time.
> Pingdom removal

- cli/Application/Command/Get/Project/Comments.php
- cli/Application/Command/Get/Project/Events.php
- cli/Application/Command/Get/Project/Issues.php
- cli/Application/Command/Update/Pulls.php
- cli/Application/Kernel/ConsoleKernel.php
- cli/tracker.php
- ruleset.xml
- src/App/Activity/Controller/Ajax/TotalActivity.php
- src/App/Support/SupportApp.php
- src/App/Text/Model/ArticlesModel.php
- src/JTracker/Application.php
- src/JTracker/EventListener/AddDebugOutputToResponseListener.php
- src/JTracker/EventListener/ErrorSubscriber.php
- src/JTracker/Github/Package/Issues.php
- src/JTracker/Kernel.php
- src/JTracker/Kernel/WebKernel.php
- src/JTracker/Twig/CdnExtension.php
- src/JTracker/Twig/FlashExtension.php
- src/JTracker/Twig/Service/CdnRenderer.php
- src/JTracker/Twig/Service/FlashMessageRetriever.php
- src/JTracker/View/BaseHtmlView.php
- tests/tracker/Hooks/Listeners/JoomlaCmsPullsListenerCheckFilesAndAssignCategoryTest.php
This fixes a bunch of codestyle issues, which we currently have and which the current codestyle ignores. In another step, we will update php_codesniffer to 3.x.
> Fixing codestyle

- .drone.yml
- ruleset.xml
This enables Drone CI for JIssues.
> Enabling Drone CI for JIssues

- composer.lock
> Updating composer dependencies

- cli/Application/Command/Update/Pulls.php
As mentiond here: https://github.com/joomla/joomla-cms/discussions/38560#discussioncomment-3454185
This here is the change from 2.5.x (which does not exists) to the 3.10-dev.
@brianteeman I can you please double check the text It should be clear right? Do you think we should link to the magazin article to explain things?
> Joomla 3.10 bot message

- composer.json
- composer.lock
> Update to phpstan 2.0
